name: EAS Update

on:
  push:
    branches:
      - master

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Configure EAS
        run: eas build:configure
        env:
          EAS_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Publish update
        run: eas update --auto
        env:
          EAS_TOKEN: ${{ secrets.EXPO_TOKEN }}

